# Generated by Django 5.1.7 on 2025-03-27 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chinook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'managed': False, 'ordering': ['album_id']},
        ),
        migrations.AlterModelOptions(
            name='artist',
            options={'managed': False, 'ordering': ['artist_id']},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'managed': False, 'ordering': ['customer_id']},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'managed': False, 'ordering': ['employee_id']},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'managed': False, 'ordering': ['track_id']},
        ),
    ]
